# Generated by Django 5.2.1 on 2025-06-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingdepartment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manufacturingmachine',
            options={'managed': False},
        ),
    ]
