# Generated by Django 5.2.1 on 2025-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_manufacturingdepartment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='is_external',
            field=models.BooleanField(default=False, help_text="Whether this remedy was performed by external technician"),
        ),
        migrations.AddField(
            model_name='remedy',
            name='technician_name',
            field=models.CharField(blank=True, help_text="Name of technician who performed the remedy", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Phone number of external technician", max_length=20, null=True),
        ),
    ]
