# Generated by Django 5.2.1 on 2025-06-27 17:55

from django.db import migrations, models


def populate_technician_names(apps, schema_editor):
    """Populate empty technician_name fields with default value"""
    Remedy = apps.get_model('issues', 'Remedy')
    Remedy.objects.filter(technician_name__isnull=True).update(technician_name='Unknown Technician')
    Remedy.objects.filter(technician_name='').update(technician_name='Unknown Technician')


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20250628_0036'),
    ]

    operations = [
        # Populate existing technician_name null values before making it required
        migrations.RunPython(populate_technician_names, migrations.RunPython.noop),
        
        # Add costing fields to Remedy model
        migrations.AddField(
            model_name='remedy',
            name='parts_purchased',
            field=models.TextField(blank=True, help_text='List of parts/items purchased for this remedy'),
        ),
        migrations.AddField(
            model_name='remedy',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Labor cost in currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total parts cost in currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total remedy cost (auto-calculated)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Update technician_name to be required
        migrations.AlterField(
            model_name='remedy',
            name='technician_name',
            field=models.CharField(max_length=100),
        ),
    ]
