# Generated by Django 5.2.1 on 2025-07-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_add_userrole_model'),
    ]

    operations = [
    ]
