# Generated by Django 5.2.1 on 2025-07-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20250701_1708'),
    ]

    operations = [
    ]
